---
- name: Install HTTP servers
  hosts: Ansible2
  become: yes

  tasks:
  - name: Install HTTPD
    yum:
      name: httpd
      state: present

  - name: Start HTTPD
    service:
      name: httpd
      state: restarted

  - name: Enable HTTPD
    service:
      name: httpd
      enabled: yes
...
