---
- name: variables
  hosts: g1
  become: yes
  vars:
     myusername: "fahim"
     mylocation: "Pakistan"

  tasks:
  - name: Update Automated page
    template:
      src: Automated.j2
      dest: /var/www/html/Automated.html
...
